apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels: 
   one: is-the-loneliest
   two: can-be-bad-as-one
spec:
  containers:
   - name: nginx2
     image: nginx:1.7.9
     ports:
     - containerPort: 80
